services:
  reviews:
    build: .
    image: ghcr.io/jobbiez/bookinfo-reviews:dev
    ports:
    - "8082:8082"
    environment:
      RATINGS_SERVICE: "http://ratings:8080/"
      ENABLE_RATINGS: "true"